name: test-workflow

on:
  issue_comment:
    types: [created, edited, deleted]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out git repository
        uses: actions/checkout@v2
      - uses: kheiakiyama/install-azcopy-action@v1
        with:
          version: 'v10'
      - run: azcopy_v10 copy latestManifest.json 'https://xmcl.blob.core.windows.net/pure-launcher' --dest-key ${{ secrets.STORAGE_KEY }}

      # - name: Azure CLI script
      #   uses: azure/CLI@v1
      #   with:
      #     azcliversion: 2.0.72
      #     inlineScript: |
      #       az storage blob upload --connection-string ${{ secrets.CONNECTION_STRING }} --container-name pure_launcher --name $GITHUB_WORKSPACE/latestManifest.json --file $GITHUB_WORKSPACE/latestManifest.json
