name: test-workflow

on:
  issue_comment:
    types: [created, edited, deleted]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out git repository
        uses: actions/checkout@v2
      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          azcliversion: 2.0.72
          inlineScript: |
            az storage blob upload --connection-string ${{ secrets.CONNECTION_STRING }} --name latestManifest.json --container-name pure_launcher --file latestManifest.json.json
